Was added slim gem
montashevych/Hostmeplease pull request #47
Opened 2021-05-22 07:39 UTC by Hunter2065

Slim HTML
Because Techsteck require it
Was added gem slim to GemFile
Yap, it was tested
![image](https://user-images.githubusercontent.com/49816584/119218618-0097e400-baea-11eb-8262-e3f5edf60bf9.png)

2021-05-22 09:24 UTC, KostyaKobel approved these changes

2021-05-22 17:23 UTC, andrjuha01 requested changes
Convert all html files to slim files in scope of this task.
Also add screenshot that application layout is correctly rendered without errors.

2021-05-22 21:02 UTC, andrjuha01 commented
you can use this resource or any similar to convert erb to slim
https://erb2slim.com/

2021-05-23 16:25 UTC, Hunter2065 commented
> Convert all html files to slim files in scope of this task.
> Also add screenshot that application layout is correctly rendered without errors.

![image](https://user-images.githubusercontent.com/49816584/119268648-8efc8a80-bbfc-11eb-9128-0536be2139a6.png)
I did it)

2021-05-23 16:27 UTC, andrjuha01 approved these changes

2021-05-23 17:20 UTC, merged