Add user registration
montashevych/Hostmeplease pull request #67
Opened 2021-05-31 20:40 UTC by KostyaKobel

# Checklist:

- [ ] Added specs for all new ruby code
- [ ] Green rspec run
- [ ] Green rubocop
- [ ] PR review from teammate

# What?
This is the Authorization page and Registration page User.

## Why?
This is necessary so that the user can go to his profile page and use our site for their respective purposes.

## How?
Install gem devise and configure him with user controller invoked on root (/) requests. A Slim view for the autorisation and registration in app/views/devise/registration/new.html.slim and app/views/devise/sessions/new.html.slim And some stylesheets for the pages as well.

## Testing?
Yes I wrote tests for the User model.

## Screenshots [(optional)](url)
http://localhost:3000/users/sign_in

## Anything Else?
You may want to delve into possible architecture changes or technical debt here. Call out challenges, optimizations, etc.

2021-06-04 07:13 UTC, Hunter2065 requested changes

2021-06-04 12:19 UTC, Hunter2065 requested changes
Will be fine if you unmerge 'demo1'

2021-06-04 14:33 UTC, andrjuha01 requested changes

2021-06-04 14:33 UTC, andrjuha01 commented on config/environments/development.rb
> +  config.action_mailer.default_url_options = { :host => 'localhost:3000', protocol: 'http' }
you have it duplicated here
https://github.com/montashevych/Hostmeplease/pull/67/files#diff-d3c4b3f41072daa416f1920511e9b2e26caea8c5cec0a14cb9508589a4dafa47R73

2021-06-04 14:33 UTC, andrjuha01 commented on config/environments/development.rb
> +  host = 'localhost:3000'
remove this one

2021-06-04 14:33 UTC, andrjuha01 commented on config/environments/production.rb
> +  heroku config:set GOOGLE_LOGIN="aleksanderis2121@gmail.com"
nooo,
use console to do that

2021-06-04 14:33 UTC, andrjuha01 commented on config/environments/production.rb
> +  host = 'https://hostmeplease.herokuapp.com/' #replace with your own url
remove this variable and set host here: https://github.com/montashevych/Hostmeplease/pull/67/files#diff-da60b4e96eff2b132991226d308949e23f4ef3aad45ad59edd09cbc32cc6251eR73

2021-06-04 14:33 UTC, andrjuha01 commented on spec/mailers/previews/user_mailer_preview.rb
> +    user = User.new(FirstName: 'Ivan', LastName: 'Bogun', email: 'ivan@gmail.com', message: 'I want to log in!')
do we need temporary user here

2021-06-04 14:33 UTC, andrjuha01 commented on spec/models/user_spec.rb
> +    let(:unvalid1_user) { build(:user, first_name: '    ') }
unvalid -> invalid
Prefer
user_without_name
user_without_password 
Than just invalid user

2021-06-04 14:33 UTC, andrjuha01 commented on db/migrate/20210527133127_devise_create_users.rb
> +      t.string   :unconfirmed_email # Only if using reconfirmable
are we using reconfirmable?
If no - remove it

2021-06-04 14:33 UTC, andrjuha01 commented on db/migrate/20210527133127_devise_create_users.rb
> +      t.string :first_name,             null: false, default: ""
Can user be created without first name?

2021-06-04 14:33 UTC, andrjuha01 commented on db/migrate/20210527133127_devise_create_users.rb
> +      t.string :email,                  null: false, default: ""
can user be created without email?

2021-06-04 16:54 UTC, andrjuha01 commented on spec/models/user_spec.rb
> +    let(:user_without_name_empty) { build(:user, first_name: '    ') }
user_with_empty_name.
Check if wording make sense

2021-06-04 17:50 UTC, VanyaNovak commented on spec/factories/users.rb
> +end
You can delete this file because it does not belong to the user model. on my branch it is already changed

2021-06-04 18:43 UTC, VanyaNovak commented
Add titles for pages

2021-06-04 19:29 UTC, VanyaNovak commented on app/views/devise/passwords/new.html.slim
> +- provide :title, "Forgott Password"
Change "Forgott" to "Forgot"

2021-06-04 19:29 UTC, VanyaNovak commented on app/views/devise/passwords/edit.html.slim
> +- provide :title, "Forgott Password"
And here change "Forgott" to "Forgot"

2021-06-04 19:34 UTC, VanyaNovak approved these changes
LGTM!

2021-06-06 11:46 UTC, KostyaKobel commented on db/migrate/20210527133127_devise_create_users.rb
> +      t.string   :unconfirmed_email # Only if using reconfirmable
Yes we will be use it

2021-06-06 16:24 UTC, Hunter2065 approved these changes
okay, but I do not vouch for it

2021-06-06 18:13 UTC, andrjuha01 commented on .github/workflows/workflow.yml
> +          gem install bundler
remove trailing spaces

2021-06-06 18:13 UTC, andrjuha01 commented on config/environments/production.rb
> +    :user_name            => ENV['GMAIL_LOGIN'],
nice

2021-06-06 18:13 UTC, andrjuha01 commented on config/environments/production.rb
> +  config.action_mailer.default_url_options = { host: ENV['HEROK_HOST'] }
HEROKU_HOST

2021-06-06 18:13 UTC, andrjuha01 commented on docker-compose.yml
> +      - "5431:5431"
hmm, that's something wrong here.
Inner port should be 5432, outer can be anything.

2021-06-06 18:13 UTC, andrjuha01 commented on app/assets/stylesheets/fonts.scss
> +@import url('https://fonts.googleapis.com/css2?family=Material+Icons');
always leave last line empty
https://stackoverflow.com/a/2287990

2021-06-06 18:16 UTC, andrjuha01 commented on app/views/layouts/application.html.slim
> +    script src="https://unpkg.com/@popperjs/core@2"
leave only one

2021-06-06 21:10 UTC, andrjuha01 commented on Gemfile
> +  gem 'sqlite3', '~> 1.4'
remove

2021-06-06 21:11 UTC, andrjuha01 commented on app/assets/stylesheets/alert.scss
> +  top: 16px;
remove app/assets/images/place-background.png

2021-06-06 21:11 UTC, andrjuha01 commented on app/controllers/users_controller.rb
> +  def index
add new line

2021-06-06 21:13 UTC, andrjuha01 commented on app/views/layouts/application.html.slim
> +    = stylesheet_link_tag 'https://fonts.googleapis.com/css2?family=Montserrat:wght@100;700&display=swap', media: 'all', 'data-turbokinks-track': 'reload'
move to separate file

2021-06-06 21:14 UTC, andrjuha01 commented on config/application.rb
>  require_relative 'boot'
app/views/users/index.html.slim
app/views/users/show.html.slim
are they empty?

2021-06-06 21:15 UTC, andrjuha01 commented on config/routes.rb
> +  resources :places
remove from line #2 same definition

2021-06-06 21:15 UTC, andrjuha01 commented on db/migrate/20210527133127_devise_create_users.rb
> +      t.string :encrypted_password,     null: false, default: ""
can user be created without password

2021-06-06 21:16 UTC, andrjuha01 commented on package-lock.json
> +{
do we need this file?

2021-06-07 08:54 UTC, KostyaKobel commented on package-lock.json
> +{
Yes. I had an error not booting normally bootstrap and css styles per page

2021-06-07 09:02 UTC, KostyaKobel commented on config/application.rb
>  require_relative 'boot'
Yes, we don't have a user profile yet. That's why they're empty now.

2021-06-08 07:49 UTC, andrjuha01 approved these changes

2021-06-09 08:13 UTC, andrjuha01 approved these changes

2021-06-09 08:13 UTC, andrjuha01 commented on spec/rails_helper.rb
> +require 'support/factory_bot'
is this required?

2021-06-09 09:59 UTC, merged

2021-06-27 08:15 UTC, KostyaKobel commented on spec/rails_helper.rb
> +require 'support/factory_bot'
Fixed