Change db to postgresql
montashevych/Hostmeplease pull request #74
Opened 2021-06-07 02:50 UTC by VanyaNovak

# Checklist:

- [x] Added specs for all new ruby code
- [x] Green rspec run
- [x] Green rubocop
- [ ] PR review from teammate

# What?
Was changed db from sqlite3 to postgresql

## Why?
Before we used pg only in production, but now we need to use it locally for simplicity

## How?
`rails db:system:change --to=postgresql`

## Testing?
nope

## Screenshots (optional)

## Anything Else?
Yep. 

- You must install postgresql to get started https://www.postgresql.org/download/
- Next you need to enter the following command in the terminal `sudo -u postgres createuser --superuser Myname`
P.S. Change Myname to your username like `gelvan`@gelvan-Laptop in your terminal)

2021-06-07 08:12 UTC, KostyaKobel requested changes
Add the ENV variables to the database and username variables

2021-06-07 11:45 UTC, montashevych commented on config/database.yml
> +  encoding: unicode
we don't need repeat this information, you can use <<: *default + url + mb database name.

2021-06-07 11:45 UTC, montashevych commented on config/database.yml
> +  encoding: unicode
I think we need "timeout" params in default or in production. Have you tried run docker-compose with this params? If my remember is correct, I had some problem with this.

2021-06-07 11:48 UTC, VanyaNovak commented on config/database.yml
> +  encoding: unicode
ok

2021-06-07 12:28 UTC, VanyaNovak commented on config/database.yml
> +  encoding: unicode
Added timeouts

2021-06-07 12:29 UTC, VanyaNovak commented on config/database.yml
> +  encoding: unicode
Refactored `database.yml `

2021-06-07 12:57 UTC, VanyaNovak commented on config/database.yml
> +  encoding: unicode
if store database name in default that will be give error

2021-06-07 13:30 UTC, montashevych approved these changes
well done I think)

2021-06-07 13:31 UTC, Hunter2065 approved these changes
I think all is good bro)

2021-06-07 13:42 UTC, KostyaKobel approved these changes
All fine

2021-06-07 13:47 UTC, andrjuha01 commented on .github/workflows/workflow.yml
>    POSTGRES_USER: postgres
can we move those to env vars?

2021-06-08 07:51 UTC, andrjuha01 commented on config/database.yml
> +  adapter: postgresql
remove adapter and encoding

2021-06-08 09:53 UTC, VanyaNovak commented on config/database.yml
> +  adapter: postgresql
Removed

2021-06-08 09:54 UTC, andrjuha01 approved these changes

2021-06-08 09:55 UTC, merged