New place
montashevych/Hostmeplease pull request #93
Opened 2021-06-13 08:06 UTC by Hunter2065

# Checklist:

- [ ] Added specs for all new ruby code
- [ ] Green rspec run
- [ ] Green rubocop
- [ ] PR review from teammate

# What?
Created page new and some mechanism for creating places

## Why?
'cause user must have this possibility.

## How?
created method new and create, also page and other things will be added in future

## Testing?
for this moment no

## Screenshots (optional)
in future

## Anything Else?
changed color of hr (header's underline) on places page for header

2021-06-13 08:59 UTC, KostyaKobel commented on app/controllers/application_controller.rb
> +        redirect_to new_user_session_url
Remove a period at the end of the line " Please log in".
And change your path on this new_user_session_path.

2021-06-13 09:02 UTC, KostyaKobel commented on app/controllers/places_controller.rb
>      @place = Place.find(params[:id])
Add private method place_find and add this string inside this method and change this string on place_find.

2021-06-13 09:08 UTC, KostyaKobel commented on app/frontend/stylesheets/header.scss
> +    color: white;
Add variable for this color because you use it in different places.

2021-06-13 09:11 UTC, KostyaKobel commented on app/frontend/stylesheets/places.scss
> +    background-color: black;
Why do you don't use rgba color?

2021-06-13 09:12 UTC, KostyaKobel commented on app/frontend/stylesheets/places.scss
> +      color: white;
And here, too, use a variable for color.

2021-06-13 09:15 UTC, KostyaKobel commented on app/views/places/new.html.slim
> +        = f.label 'Deacription'
Fix label name this

2021-06-13 09:18 UTC, KostyaKobel commented on app/views/places/new.html.slim
> +        / = f.label 'Type'
Why did you miss these two lines?Remove it if you don't use it.

2021-06-13 09:21 UTC, KostyaKobel commented on app/views/places/new.html.slim
> +      .col-lg-5
For what context do you use these two bootstrap classes?

2021-06-13 10:48 UTC, Hunter2065 commented on app/frontend/stylesheets/places.scss
> +    background-color: black;
'cause me need simple color and I think it's correctly)

2021-06-13 10:49 UTC, Hunter2065 commented on app/frontend/stylesheets/places.scss
> +      color: white;
Okay)

2021-06-13 10:49 UTC, Hunter2065 commented on app/views/places/new.html.slim
> +        = f.label 'Deacription'
Oh, okay), thanks)

2021-06-13 10:50 UTC, Hunter2065 commented on app/views/places/new.html.slim
> +        / = f.label 'Type'
Okay, I working at this

2021-06-13 10:51 UTC, Hunter2065 commented on app/views/places/new.html.slim
> +      .col-lg-5
It's for future design

2021-06-13 12:28 UTC, Hunter2065 commented on app/controllers/application_controller.rb
> +        redirect_to new_user_session_url
fixed)

2021-06-13 12:35 UTC, Hunter2065 commented on app/controllers/places_controller.rb
>      @place = Place.find(params[:id])
fixed)

2021-06-13 12:36 UTC, Hunter2065 commented on app/views/places/new.html.slim
> +        = f.label 'Deacription'
fixed)

2021-06-15 07:34 UTC, Hunter2065 commented on app/frontend/stylesheets/places.scss
> +      color: white;
ok)

2021-07-02 18:54 UTC, RMuskovets requested changes
left *some* comments

2021-07-02 18:54 UTC, RMuskovets commented on app/controllers/application_controller.rb
> +
This method is already provided by Devise: `before_action :authenticate_user!`.

2021-07-02 18:54 UTC, RMuskovets commented on app/controllers/places_controller.rb
> +    @picture = Picture.new
shouldn't it be an array of pictures?

2021-07-02 18:54 UTC, RMuskovets commented on app/controllers/places_controller.rb
> +      redirect_to my_places_path
why redirect to my places? i think, it'd be better to redirect to the place url instead:
```suggestion
      redirect_to place_path(@place)
```

2021-07-02 18:54 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +    accessToken: 'sk.eyJ1IjoiaHVudGkiLCJhIjoiY2twd3J0dDQ5MWczdTJ1bm9xeXhoZWc2eCJ9.MEGM9kySBOwTh46vZ7eTMg'
better move this to `ENV`:
```suggestion
    accessToken: '<%= ENV["MAPBOX_API_KEY"] %>'
```

2021-07-02 18:54 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +    accessToken: 'sk.eyJ1IjoiaHVudGkiLCJhIjoiY2twd3J0dDQ5MWczdTJ1bm9xeXhoZWc2eCJ9.MEGM9kySBOwTh46vZ7eTMg'
better move this to `ENV`:
```suggestion
    accessToken: '<%= ENV["MAPBOX_API_KEY"] %>'
```

2021-07-02 18:54 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +    accessToken: 'sk.eyJ1IjoiaHVudGkiLCJhIjoiY2twd3J0dDQ5MWczdTJ1bm9xeXhoZWc2eCJ9.MEGM9kySBOwTh46vZ7eTMg'
use `ENV` for API keys:
```suggestion
    accessToken: '<%= ENV["MAPBOX_API_KEY"] %>'
```

2021-07-02 18:54 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +    marker.on('click', evt => {
merge into single event handler

2021-07-02 18:54 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +  document.getElementById('address_form').addEventListener('focusout', () => {  // or event 'input' for geocoding in real time
use `change` event for this. it gets triggered after the user presses Enter key **or** focus moves out of the field.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event
```suggestion
  document.getElementById('address_form').addEventListener('change', () => {
```

2021-07-02 18:54 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +    };
use `if`/`else if`/`else` for this:
```suggestion
    if (state_region_field.value.length > 0)
      zoom = 10;
    else if (city_field.value.length > 0)
      zoom = 14;
    else if (street_field.value.length > 0)
      zoom = 16;
    else if (number_street_field.value.length > 0)
      zoom = 18;
    else
      zoom = 5;
```

2021-07-02 18:54 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +      let lng = data.results[0].geometry.location.lng;
use destructuring for this:
```suggestion
      let { lat, lng } = data.results[0].geometry.location;
```

2021-07-02 18:54 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +    let n = Array.from(event.target.files);
rename to something more meaningful, like `files`
```suggestion
    let files = Array.from(event.target.files);
```

2021-07-02 18:54 UTC, RMuskovets commented on app/views/layouts/application.html.slim
> +    script src='https://unpkg.com/leaflet@1.7.1/dist/leaflet.js'
can't you just install it via NPM?

2021-07-02 18:58 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +    accessToken: 'sk.eyJ1IjoiaHVudGkiLCJhIjoiY2twd3J0dDQ5MWczdTJ1bm9xeXhoZWc2eCJ9.MEGM9kySBOwTh46vZ7eTMg'
In green line you can see that)

2021-07-02 19:02 UTC, KostyaKobel requested changes

2021-07-02 19:02 UTC, KostyaKobel commented on app/controllers/places_controller.rb
> +    place_find
Remove it and add to before action method.

2021-07-02 19:16 UTC, KostyaKobel requested changes

2021-07-02 19:16 UTC, KostyaKobel commented on app/controllers/places_controller.rb
>      @place = Place.find(params[:id])
Fixed it

2021-07-02 19:19 UTC, Hunter2065 commented on app/controllers/places_controller.rb
> +    @picture = Picture.new
Noooo, we have one picture, but array IMAGES))

2021-07-02 19:33 UTC, Hunter2065 commented on app/controllers/application_controller.rb
> +
fixed)

2021-07-02 19:35 UTC, Hunter2065 commented on app/controllers/places_controller.rb
> +      redirect_to my_places_path
fixed)

2021-07-02 19:37 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +    accessToken: 'sk.eyJ1IjoiaHVudGkiLCJhIjoiY2twd3J0dDQ5MWczdTJ1bm9xeXhoZWc2eCJ9.MEGM9kySBOwTh46vZ7eTMg'
resolved)

2021-07-02 19:42 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +  document.getElementById('address_form').addEventListener('focusout', () => {  // or event 'input' for geocoding in real time
fixed)

2021-07-02 19:45 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +    };
fixed

2021-07-02 19:46 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +      let lng = data.results[0].geometry.location.lng;
fixed

2021-07-02 19:47 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +    let n = Array.from(event.target.files);
It's correct?) okay), fixed)

2021-07-02 19:49 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +    marker.on('click', evt => {
skiped)

2021-07-02 19:50 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +    marker.on('click', evt => {
actually not needed, looks like i need some sleep

2021-07-02 19:51 UTC, Hunter2065 commented on app/controllers/places_controller.rb
> +    place_find
resolved

2021-07-02 19:55 UTC, Hunter2065 commented on app/controllers/places_controller.rb
>      @place = Place.find(params[:id])
fixed

2021-07-03 13:23 UTC, Hunter2065 commented on app/views/layouts/application.html.slim
> +    script src='https://unpkg.com/leaflet@1.7.1/dist/leaflet.js'
fixed)

2021-07-03 18:58 UTC, RMuskovets requested changes
some more comments

2021-07-03 18:58 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +  let geocoder = require('geocoder');                // require geocoder library
why `require`? we use ES6 `import`!

2021-07-03 18:58 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +    shadowUrl: require('leaflet/dist/images/marker-shadow.png'),          //*
also here. but for dynamic imports you can use the `import("path")` function, which returns a promise.

2021-07-03 18:58 UTC, RMuskovets commented on app/frontend/js/newplace.js.erb
> +window.newPlacePage = () => {
use separate packs for each page

2021-07-03 18:58 UTC, RMuskovets commented on app/frontend/packs/application.js
> +import '../js/newplace.js.erb'
make newplace.js.erb a separate pack and do not import it here

2021-07-04 09:49 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +  let geocoder = require('geocoder');                // require geocoder library
resolved)

2021-07-04 10:17 UTC, KostyaKobel commented on app/views/places/new.html.slim
> +        / = form_for(@place) do |f|
If you doesn't use it,removed these strings.

2021-07-04 10:23 UTC, KostyaKobel commented on app/frontend/stylesheets/places.scss
>      justify-content: center;
If you don't use here display: flex; it style doesn't work there.And why you don't use bootstrap styles for it?

2021-07-04 10:27 UTC, KostyaKobel commented on app/views/places/new.html.slim
> +          .col-lg-5.justify-content-start
Where do you use bootstrap d.flex?Your styles correct working?

2021-07-04 10:30 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +window.newPlacePage = () => {
resolved)

2021-07-04 10:30 UTC, Hunter2065 commented on app/frontend/packs/application.js
> +import '../js/newplace.js.erb'
resolved)

2021-07-04 10:35 UTC, Hunter2065 commented on app/views/places/new.html.slim
> +        / = form_for(@place) do |f|
![image](https://user-images.githubusercontent.com/49816584/124381710-a08d8380-dccc-11eb-9a82-d55691ab33f0.png)
say me please where you found it?) in first commit?)

2021-07-04 10:35 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +    shadowUrl: require('leaflet/dist/images/marker-shadow.png'),          //*
resolved)

2021-07-04 10:40 UTC, Hunter2065 commented on app/frontend/stylesheets/places.scss
>      justify-content: center;
![image](https://user-images.githubusercontent.com/49816584/124381875-5789ff00-dccd-11eb-883b-09cd524c1ced.png)
where you found that???)))) In first commit?)

2021-07-04 10:46 UTC, Hunter2065 commented on app/frontend/stylesheets/places.scss
>      justify-content: center;
special for you I can say, what  bootstrap's 'row' is flex-element)

2021-07-04 10:48 UTC, Hunter2065 commented on app/views/places/new.html.slim
> +          .col-lg-5.justify-content-start
yap, all my styles is correct and can work)

2021-07-04 10:49 UTC, KostyaKobel commented on app/frontend/js/newplace.js.erb
> +    };
You don't correct use else if.Search this link: https://stackoverflow.com/questions/31859386/can-i-use-else-if-over-elsif how use it

2021-07-04 11:21 UTC, RMuskovets approved these changes
_now_ it's LGTM.

2021-07-04 11:27 UTC, KostyaKobel commented on app/frontend/js/newplace.js.erb
> +    let address_string = `${ country }, ${ city_field.value }, ` +
What is it "+" in end line?

2021-07-04 11:32 UTC, KostyaKobel commented on app/views/places/new.html.slim
> +        / = form_for(@place) do |f|
Maybe

2021-07-04 12:27 UTC, Hunter2065 commented on app/frontend/js/newplace.js.erb
> +    let address_string = `${ country }, ${ city_field.value }, ` +
JS basics

2021-07-04 12:28 UTC, KostyaKobel approved these changes
Now it's looked at fine.

2021-07-05 10:28 UTC, RMuskovets approved these changes

2021-07-05 21:08 UTC, andrjuha01 commented on app/controllers/places_controller.rb
> +    @place = Place.new
just try to do something like this
@place = Place.new
@place.address.build
@place.picture.build

It will create connections between associations.

2021-07-05 21:08 UTC, andrjuha01 commented on app/controllers/places_controller.rb
> +    place_build && address_build && picture_build
use nested attributes for it
https://stackoverflow.com/a/19230764

2021-07-05 21:08 UTC, andrjuha01 commented on app/frontend/packs/application.js
> +import 'leaflet/dist/leaflet.css'
is it working inside docker?

2021-07-05 21:08 UTC, andrjuha01 commented on app/frontend/packs/new.js.erb
> +let latlng = [0.0, 0.0];
try to extract this into more methods.
It is not really readable right now

2021-07-05 21:08 UTC, andrjuha01 commented on app/helpers/places_helper.rb
> +  def full_address(address_hash)
specs?

2021-07-05 21:08 UTC, andrjuha01 commented on spec/controllers/places_controller_spec.rb
> +    let(:test_user) { FactoryBot.create(:user, :confirmed) }
where do you test all actions?
don't see here specs for creating place

2021-07-05 21:08 UTC, andrjuha01 commented on spec/controllers/places_controller_spec.rb
> +      test_picture.destroy
aren't we using transactional features?
Or database cleaner at least?

2021-07-05 21:08 UTC, andrjuha01 commented on spec/factories/pictures.rb
> +      [Rack::Test::UploadedFile.new(
formatting

2021-07-06 05:22 UTC, Hunter2065 commented on spec/factories/pictures.rb
> +      [Rack::Test::UploadedFile.new(
this is rubocop formatting

2021-07-06 05:31 UTC, Hunter2065 commented on app/controllers/places_controller.rb
> +    @place = Place.new
resolved)

2021-07-06 13:26 UTC, RMuskovets approved these changes

2021-07-11 08:58 UTC, Hunter2065 commented on app/controllers/places_controller.rb
> +    place_build && address_build && picture_build
fiiiiiixed))

2021-07-11 14:48 UTC, Hunter2065 commented on app/helpers/places_helper.rb
> +  def full_address(address_hash)
yap), I wrote test for this)

2021-07-12 09:28 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +    let(:test_user) { FactoryBot.create(:user, :confirmed) }
now it's done)

2021-07-13 06:13 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +      test_picture.destroy
resolved

2021-07-13 19:16 UTC, Hunter2065 commented on app/frontend/packs/application.js
> +import 'leaflet/dist/leaflet.css'
yap)))), it's work)

2021-07-15 15:31 UTC, Hunter2065 commented on app/frontend/packs/new.js.erb
> +let latlng = [0.0, 0.0];
decided how I can)

2021-07-16 08:19 UTC, andrjuha01 commented on app/models/place.rb
> +  # for production must change description minimum to 100 characters
validations should be same for prod and dev

2021-07-16 08:19 UTC, andrjuha01 commented on app/models/place.rb
> +  # geocoded_by full_address(@address) do |obj, results|
remove if not used

2021-07-16 08:19 UTC, andrjuha01 commented on app/models/place.rb
> +    if user.places.count.zero? && user.owner?
don't use `count.zero?`, please familiarize with `exists?` and why to use `exists` in cases like this

2021-07-16 08:19 UTC, andrjuha01 commented on app/models/user.rb
> +  has_many :places, dependent: :destroy
put relations before validations

2021-07-16 08:19 UTC, andrjuha01 commented on app/views/places/_my_place.html.slim
> +          p.mb-2.font_family_price = "$#{'%.2f' % place.price}"
we need to fix `price` column. This should not be on `FE`

2021-07-16 08:19 UTC, andrjuha01 commented on db/seeds.rb
> +20.times do |n|
add some puts so we know what is happening

```
rails db:seed

=> Starting seeding
=> Seeding user #{user.email}
=> Seeding places #{place.title}
=> Seeding is finished

2021-07-16 08:19 UTC, andrjuha01 commented on spec/controllers/places_controller_spec.rb
> +  let(:test_place) {
use `do end` if multiline assignment

2021-07-16 08:19 UTC, andrjuha01 commented on spec/controllers/places_controller_spec.rb
> +    Rack::Test::UploadedFile.new(
same

2021-07-16 08:19 UTC, andrjuha01 commented on spec/controllers/places_controller_spec.rb
> +      expect(test_user).to be_valid
what are you testing here?

2021-07-16 08:19 UTC, andrjuha01 commented on spec/controllers/places_controller_spec.rb
> +      parameters = test_place.attributes
use let to prepare params
let(:parameters) { FactoryBot.attributes_for(:test_place, your_attributes_goes_here)

Or add new trait to factory and use
let(:parameters) { FactoryBot.attributes_for(:test_place, :with_address, :with_pictures)

2021-07-16 08:19 UTC, andrjuha01 commented on spec/controllers/places_controller_spec.rb
> +  context 'when User is login and' do
and ?

2021-07-16 08:19 UTC, andrjuha01 commented on spec/controllers/places_controller_spec.rb
> +      post :create, params: { place: test_place.attributes,
assign params in let(as described above)

2021-07-16 08:19 UTC, andrjuha01 commented on spec/controllers/places_controller_spec.rb
> +      expect(response.content_type) == 'text/html'
.to eq('text/html')

2021-07-16 08:19 UTC, andrjuha01 commented on spec/feature/place_spec.rb
> +      # binding.pry
remove

2021-07-16 08:19 UTC, andrjuha01 commented on spec/views/places/_my_place.html.slim_spec.rb
> +  let!(:test_place) {
do end

2021-07-16 09:16 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +      expect(response.content_type) == 'text/html'
Rubocop prohibits use this method)

2021-07-16 09:16 UTC, Hunter2065 commented on spec/feature/place_spec.rb
> +      # binding.pry
Wow, okay

2021-07-16 09:32 UTC, Hunter2065 commented on app/models/place.rb
> +  # for production must change description minimum to 100 characters
resolved

2021-07-16 09:32 UTC, Hunter2065 commented on app/models/place.rb
> +  # geocoded_by full_address(@address) do |obj, results|
resolved

2021-07-16 09:33 UTC, Hunter2065 commented on app/models/place.rb
> +    if user.places.count.zero? && user.owner?
'cause if user delete last place, then has role 'consumer', but hasn't any place

2021-07-16 09:35 UTC, Hunter2065 commented on app/models/place.rb
> +    if user.places.count.zero? && user.owner?
resolved)

2021-07-16 09:36 UTC, Hunter2065 commented on app/models/user.rb
> +  has_many :places, dependent: :destroy
resolved)

2021-07-16 09:39 UTC, Hunter2065 commented on app/views/places/_my_place.html.slim
> +          p.mb-2.font_family_price = "$#{'%.2f' % place.price}"
of course, but seeds can did very long price

2021-07-16 09:41 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +      expect(test_user).to be_valid
I forget), resolved)

2021-07-16 09:44 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +  let(:test_place) {
resolved)

2021-07-16 09:44 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +    Rack::Test::UploadedFile.new(
resolved)

2021-07-16 12:33 UTC, Hunter2065 commented on spec/feature/place_spec.rb
> +      # binding.pry
resolved)

2021-07-16 12:33 UTC, Hunter2065 commented on spec/views/places/_my_place.html.slim_spec.rb
> +  let!(:test_place) {
resolved)

2021-07-16 12:59 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +  context 'when User is login and' do
it's not my test, 'cause I don't know, but resolved it)

2021-07-16 13:01 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +      post :create, params: { place: test_place.attributes,
how?

2021-07-16 13:06 UTC, Hunter2065 commented on db/seeds.rb
> +20.times do |n|
resolved)

2021-07-16 14:26 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +      expect(response.content_type) == 'text/html'
resolved)

2021-07-16 14:39 UTC, Hunter2065 commented on app/views/places/_my_place.html.slim
> +          p.mb-2.font_family_price = "$#{'%.2f' % place.price}"
resolved)

2021-07-16 15:49 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +      parameters = test_place.attributes
resolved)

2021-07-16 15:53 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
> +      post :create, params: { place: test_place.attributes,
also resolved)

2021-07-17 07:52 UTC, andrjuha01 commented on app/controllers/places_controller.rb
> +  before_action :authenticate_user!, only: [:new, :create, :my_places, :destroy]
Only receives too many actions. Probably use except

2021-07-17 07:52 UTC, andrjuha01 commented on public/404.html
> -<!DOCTYPE html>
Why this is removed?

2021-07-17 07:52 UTC, andrjuha01 commented on spec/controllers/places_controller_spec.rb
>  RSpec.describe PlacesController do
Add specs for unauthenticated user

2021-07-17 10:42 UTC, Hunter2065 commented on app/controllers/places_controller.rb
> +  before_action :authenticate_user!, only: [:new, :create, :my_places, :destroy]
resolved)

2021-07-17 10:47 UTC, Hunter2065 commented on public/404.html
> -<!DOCTYPE html>
oh, it's a coincidence, I restored these files

2021-07-17 12:39 UTC, Hunter2065 commented on spec/controllers/places_controller_spec.rb
>  RSpec.describe PlacesController do
resolved)

2021-07-17 12:45 UTC, andrjuha01 approved these changes

2021-07-17 13:06 UTC, merged