Add myplaces list in profile
montashevych/Hostmeplease pull request #96
Opened 2021-06-17 09:23 UTC by KostyaKobel

# Checklist:

- [ ] Added specs for all new ruby code
- [ ] Green rspec run
- [ ] Green rubocop
- [ ] PR review from teammate

# What?
Add my places list in a Profile Page for Owner Place. 

## Why?
These changes will add each Owner who has Place  opportunity to see a list of their places.

## How?
When creating a new place user will be Owner this place and for him will be add opportunity see him places list on My Places page.

## Testing?
Yes, I did.

## Screenshots (optional)
![Uploading MyPlaces.png…]()

## Anything Else?

2021-06-20 10:09 UTC, andrjuha01 commented on app/frontend/stylesheets/header.scss
> +}
new line

2021-06-20 10:09 UTC, andrjuha01 commented on app/models/place.rb
> +  belongs_to :user, optional: true
so place can be created without user?
I don't think that it is right

2021-06-20 10:09 UTC, andrjuha01 commented on app/models/user.rb
> +  VALID_EMAIL_REGEX = /\A[^@\s]+@[^@\s]+\z/
Use devise validations for email and password

2021-06-20 10:09 UTC, andrjuha01 commented on app/views/places/my_places.html.slim
> +	.container
why tabs are too wide now?

2021-06-20 10:09 UTC, andrjuha01 commented on app/controllers/places_controller.rb
> +  def new; end
do you use new and edit endpoints?

2021-06-20 10:12 UTC, KostyaKobel commented on app/controllers/places_controller.rb
> +  def new; end
Yes I do.I add rspec tests where I need add these actions in controller.

2021-06-20 12:07 UTC, Hunter2065 reviewed
![image](https://user-images.githubusercontent.com/49816584/122673459-3a3b3800-d1d9-11eb-9adf-fcf4cbf7587e.png)
you must change link to editing place

2021-06-20 12:10 UTC, Hunter2065 reviewed
![image](https://user-images.githubusercontent.com/49816584/122673496-5f2fab00-d1d9-11eb-8059-33b0d2bfa60e.png)
will be good if you can add greater retreat to bottom

Fixed

2021-06-20 12:11 UTC, Hunter2065 reviewed
![image](https://user-images.githubusercontent.com/49816584/122673579-b59ce980-d1d9-11eb-82fe-1bb0d5d7858c.png)
it's not good

2021-06-20 12:18 UTC, Hunter2065 requested changes
![image](https://user-images.githubusercontent.com/49816584/122673606-d9602f80-d1d9-11eb-8245-36fe61a221db.png)
change position filters' dropdown-list to center

![image](https://user-images.githubusercontent.com/49816584/122673643-10364580-d1da-11eb-8bbd-4a7e8e819436.png)
it's not good(
![image](https://user-images.githubusercontent.com/49816584/122673658-26440600-d1da-11eb-8aff-524cf55e8926.png)
it's too, please make it more in responsible design

![image](https://user-images.githubusercontent.com/49816584/122673721-715e1900-d1da-11eb-8981-fad0ee1dd31a.png)
my phone will not approve that(

Fixed

2021-06-20 12:28 UTC, Hunter2065 requested changes

2021-06-20 12:28 UTC, Hunter2065 commented on Gemfile
> +gem 'mini_magick', '~> 4.11'
do you use  these?

2021-06-20 12:28 UTC, Hunter2065 commented on spec/views/places/_my_place.html.slim_spec.rb
> +end
I think this test for template, not for partial, 'cause it's part of template

2021-06-21 10:22 UTC, Hunter2065 reviewed
![image](https://user-images.githubusercontent.com/49816584/122747412-b2feca80-d293-11eb-85d3-b8cda2e615c9.png)
your will_paginate must be like this

2021-06-22 14:13 UTC, KostyaKobel commented on app/frontend/stylesheets/header.scss
> +}
Fixed

2021-06-22 14:13 UTC, KostyaKobel commented on app/models/place.rb
> +  belongs_to :user, optional: true
Fixed

2021-06-22 14:13 UTC, KostyaKobel commented on app/models/user.rb
> +  VALID_EMAIL_REGEX = /\A[^@\s]+@[^@\s]+\z/
Fixed

2021-06-22 14:14 UTC, KostyaKobel commented on Gemfile
> +gem 'mini_magick', '~> 4.11'
Fixed

2021-06-22 14:19 UTC, KostyaKobel commented on Gemfile
> +gem 'mini_magick', '~> 4.11'
Fixed

2021-06-24 12:48 UTC, KostyaKobel commented on spec/views/places/_my_place.html.slim_spec.rb
> +end
Fixed

2021-06-24 16:25 UTC, Hunter2065 requested changes
![image](https://user-images.githubusercontent.com/49816584/123298917-aa232880-d521-11eb-9632-fa1ecfe10605.png)
Opps, when user hasn't places page must looks like this:
![image](https://user-images.githubusercontent.com/49816584/123299229-f8d0c280-d521-11eb-83e6-70164f0df7cc.png)

2021-06-24 16:38 UTC, Hunter2065 requested changes
resolve some issues in comments

2021-06-24 16:38 UTC, Hunter2065 commented on app/frontend/stylesheets/places.scss
> +    color: #505050 !important;
i think using important is not a good practice

2021-06-24 16:38 UTC, Hunter2065 commented on app/frontend/stylesheets/places.scss
> +          @media (min-width: 1400px) and (max-width: 1920px ) {
it's tooo many media-requests), can we use less requests?) just we use bootstrap for responsible-adaptive design

2021-06-24 16:38 UTC, Hunter2065 commented on config/initializers/carrier_wave.rb
> +end
remove this file!!

2021-06-24 17:42 UTC, KostyaKobel commented on app/frontend/stylesheets/places.scss
> +          @media (min-width: 1400px) and (max-width: 1920px ) {
If I need use it I use.

2021-06-24 18:02 UTC, KostyaKobel commented on config/initializers/carrier_wave.rb
> +end
Fixed

2021-06-24 18:03 UTC, KostyaKobel commented on app/frontend/stylesheets/places.scss
> +    color: #505050 !important;
It good practice when I need use it.

2021-06-24 20:41 UTC, andrjuha01 commented on app/frontend/stylesheets/places.scss
> +    color: #505050 !important;
you can specify better selector to not use !important. Please try to fix it

2021-06-25 04:28 UTC, Hunter2065 commented on app/frontend/stylesheets/places.scss
> +          @media (min-width: 1400px) and (max-width: 1920px ) {
why only you have so?

2021-06-25 09:02 UTC, Hunter2065 commented on app/models/user.rb
> +  validates :password, length: { minimum: 6, maximum: 256 }
presence must be, 'cause without it the errors do not return in flash-messages

2021-06-25 09:03 UTC, Hunter2065 reviewed
some comment

2021-06-25 13:59 UTC, KostyaKobel commented on app/models/user.rb
> +  validates :password, length: { minimum: 6, maximum: 256 }
If we use minimum and maximum length we don't need use validation  check on presence.And flash-messages present for registration User.

2021-06-25 14:32 UTC, KostyaKobel commented on app/frontend/stylesheets/places.scss
> +    color: #505050 !important;
Fixed

2021-06-26 18:39 UTC, Hunter2065 reviewed
![image](https://user-images.githubusercontent.com/49816584/123522619-fcea1500-d6c6-11eb-8b3a-e97e6d985e43.png)
change please color in comment

2021-06-28 07:06 UTC, Hunter2065 requested changes
![image](https://user-images.githubusercontent.com/49816584/123594530-7d5c6300-d7f8-11eb-813e-0f7122b053e7.png)
?

2021-06-28 07:45 UTC, andrjuha01 approved these changes

2021-06-28 11:38 UTC, Hunter2065 approved these changes
I think all is good now

2021-06-28 11:59 UTC, merged